### ISSUE TITLE
Standard output is not shown on notebook

### ISSUE THREAD

**Issue by haochenx** [joeltg/mit-scheme-kernel#1]
Thanks for the awesome work!

I just tried your project and I'm considering using it in a seminar on SICP. One thing I noticed is that the standard output is not redirected to the notebook (e.g. `(display '(1 2 3 4))` would return `#!unspecific ` as the result.) Is it possible to have the output also shown on the notepad?

**Comment by joeltg** [comment]
Hmm... Are you using docker or using it natively? Are you sure it's the most recent version? Seems to work for me...
![screenshot from 2017-06-02 17-18-01](https://cloud.githubusercontent.com/assets/8454646/26746896/151af74a-47b8-11e7-95d5-48e5081c60e5.png)

**Comment by joeltg** [comment]
> `(display '(1 2 3 4))` would return `#!unspecific` as the result

`display` and `pp` and most standard output procedures all return `#!unspecific`; they just have the side effect of writing to stdio. So `(eq? (display "hi") #!unspecific)` is `#t` even though it also prints "hi". You see this reflected above where
```scheme
(display '(1 2 3 4))
5
```
prints `(1 2 3 4)` but its output is `Out[2]: 5`, while just `(pp "hello world")` doesn't have an `Out[1]` value because it returns `#!unspecific`, which the notebook (like the console) ignores.

**Comment by haochenx** [comment]
Sorry I wasn't able to reply more timely. Yes I was using the docker image linked on the homepage. I'll try the newest version and see whether the problem persists.

We've decided to use Calysto Scheme for now but since it has its own problems (it's not 100% scheme) we may switch back.
